# Generated by Django 3.1.6 on 2021-02-04 01:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('hourlyRate', models.PositiveIntegerField()),
                ('areas', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Coaches',
            },
        ),
    ]
